export const CATEGORY_HIERARCHY = [
  {
    id: 'sport',
    label: 'Sport',
    icon: '⚽',
    subs: [
      { name: 'Fußball', icon: '⚽' },
      { name: 'Basketball', icon: '🏀' },
      { name: 'Volleyball', icon: '🏐' },
      { name: 'Beachvolleyball', icon: '🏐' },
      { name: 'Tennis', icon: '🎾' },
      { name: 'Badminton', icon: '🏸' },
      { name: 'Tischtennis', icon: '🏓' },
      { name: 'Golf', icon: '⛳' },
      { name: 'Running', icon: '🏃' },
      { name: 'Fitness', icon: '💪' },
      { name: 'Yoga', icon: '🧘' },
      { name: 'Schwimmen', icon: '🏊' },
      { name: 'Eislaufen', icon: '⛸️' },
      { name: 'Kampfsport', icon: '🥋' },
      { name: 'Boxen', icon: '🥊' },
      { name: 'Reiten', icon: '🏇' },
    ],
  },
  {
    id: 'night-out',
    label: 'Night Out',
    icon: '🌙',
    subs: [
      { name: 'Bar-Hopping', icon: '🍺' },
      { name: 'Clubbing', icon: '🎧' },
      { name: 'Tanzen', icon: '💃' },
      { name: 'Karaoke', icon: '🎤' },
      { name: 'Cocktails', icon: '🍹' },
      { name: 'Rooftop', icon: '🌆' },
      { name: 'Konzert', icon: '🎵' },
      { name: 'After Work', icon: '💼' },
      { name: 'Pub Quiz', icon: '🧠' },
      { name: 'Comedy Show', icon: '😂' },
      { name: 'Networking', icon: '🤝' },
    ],
  },
  {
    id: 'outdoor',
    label: 'Outdoor',
    icon: '🏕️',
    subs: [
      { name: 'Wandern', icon: '🏔️' },
      { name: 'Radfahren', icon: '🚴' },
      { name: 'Mountainbiken', icon: '🚵' },
      { name: 'Klettern', icon: '🧗' },
      { name: 'Skifahren', icon: '⛷️' },
      { name: 'Snowboarden', icon: '🏂' },
      { name: 'Langlaufen', icon: '🎿' },
      { name: 'Camping', icon: '🏕️' },
      { name: 'Paragliding', icon: '🪂' },
      { name: 'Kanufahren', icon: '🛶' },
      { name: 'Segeln', icon: '⛵' },
      { name: 'Picknick', icon: '🧺' },
    ],
  },
  {
    id: 'kultur',
    label: 'Kultur',
    icon: '🎭',
    subs: [
      { name: 'Musik', icon: '🎵' },
      { name: 'Konzerte', icon: '🎼' },
      { name: 'Theater', icon: '🎭' },
      { name: 'Oper', icon: '🎻' },
      { name: 'Kunst', icon: '🎨' },
      { name: 'Museen', icon: '🏛️' },
      { name: 'Fotografie', icon: '📸' },
      { name: 'Film', icon: '🎬' },
      { name: 'Bücher', icon: '📚' },
      { name: 'Brettspiele', icon: '🎲' },
      { name: 'Escape Room', icon: '🔐' },
      { name: 'Stadtführung', icon: '🗺️' },
      { name: 'Sprachen', icon: '🗣️' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    icon: '🍳',
    subs: [
      { name: 'Essen gehen', icon: '🍽️' },
      { name: 'Brunch', icon: '🥞' },
      { name: 'Kochen', icon: '🍳' },
      { name: 'Backen', icon: '🍰' },
      { name: 'Grillabend', icon: '🔥' },
      { name: 'Food-Touren', icon: '🍜' },
      { name: 'Street Food', icon: '🌮' },
      { name: 'Heuriger', icon: '🍾' },
      { name: 'Weinverkostung', icon: '🍷' },
      { name: 'Bierverkostung', icon: '🍺' },
      { name: 'Kaffee', icon: '☕' },
      { name: 'Veganes Essen', icon: '🥗' },
    ],
  },
  {
    id: 'sonstiges',
    label: 'Sonstiges',
    icon: '✨',
    subs: [
      { name: 'Reisen', icon: '✈️' },
      { name: 'Shopping', icon: '🛍️' },
      { name: 'Flohmarkt', icon: '🗃️' },
      { name: 'Gaming', icon: '🎮' },
      { name: 'Tiere', icon: '🐾' },
      { name: 'Meditation', icon: '🧘' },
      { name: 'Freiwilligenarbeit', icon: '🤲' },
      { name: 'Sonstiges', icon: '✨' },
    ],
  },
];
